version: "3.8"

services:
  backend-blue:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:latest
    environment:
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      REPORT_PATH: /app/reports
      LOG_PATH : /app/logs
    restart: always
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

  backend-green:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:latest
    environment:
      VIRTUAL_HOST: "backend"
      VIRTUAL_PORT: "8080"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      REPORT_PATH: /app/reports
      LOG_PATH : /app/logs
    restart: always
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6

  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    restart: always
    environment:
      PORT: 8080
      DB: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-store

  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:latest
    container_name: sausage-store-frontend
    restart: always
    environment:
      DEFAULT_HOST: "backend"
    ports:
      - "80:80"
    networks:
      - sausage-store
    volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  sausage-store: